In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import math
%matplotlib inline

#### Уровень 0:







#### Создайте матрицу 3 на 3, заполненную числами от 1 до 9

In [23]:
matrix_3_3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Матрица 3 на 3:\n',matrix_3_3)

Матрица 3 на 3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Прибавьте к ней матрицу с единицами на диагонале 

In [22]:
matrix_ones = np.identity(3)
matrix_sum = matrix_ones+matrix_3_3
print('Сумма матриц:\n',matrix_sum)

Сумма матриц:
 [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]


#### Умножьте полученную матрицу на вектор (1, 2, 3)

In [19]:
vector = np.array([1,2,3])
print('Вектор:', vector)
result_umn = matrix_sum.dot(vector)
print('Полученый в результате умножения вектор:',result_umn)




Вектор: [1 2 3]
Полученый в результате умножения вектор: [15. 34. 53.]


#### Посчитайте обратную матрицу к полученной матрице

In [21]:
matrix_inv = np.linalg.inv(matrix_sum)
print('Обратная матрица:\n',matrix_inv)

Обратная матрица:
 [[-6.00000000e+00 -2.00000000e+00  3.00000000e+00]
 [-1.00000000e+00  5.00000000e-01  2.22044605e-17]
 [ 5.00000000e+00  1.00000000e+00 -2.00000000e+00]]
