# Домашнее задание**






In [2]:
import numpy as np

**Задание 1**
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).



In [12]:
#Первое, но Длинное решение:
n = 10
a = np.arange( 0, n)
#print(a,type(a))#Control
a_list = list(a)
r_list = list(reversed(a_list))
b = np.array(r_list)
print(b, type(b))

[9 8 7 6 5 4 3 2 1 0] <class 'numpy.ndarray'>


In [13]:
#Второе решение- короче
n = 10
a = np.arange( 0, n)
print(a,type(a))#Control
b =a[::-1]
print(b, type(b))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[9 8 7 6 5 4 3 2 1 0] <class 'numpy.ndarray'>


In [14]:
#Третье решение- через цикл
n = 10
a = np.arange( 0, n)
print(a,type(a))#Control
i = 0
rev_list= []
for element in a:
    i +=1
    rev_list.append(a[n-i])
    
b = np.array(rev_list)
print(b, type(b))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[9 8 7 6 5 4 3 2 1 0] <class 'numpy.ndarray'>


**Задание 2**
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [124]:
m = np.diag(b)#numpy_array с элементами от N до 0 взят из предыдущих заданий(переменная b) 
print(m)
diag_sum=0
i=0
for item in m:
    diag_sum += item[i]
    #print(item[i])#Control
    i+=1
    
print('Сумма значений по диагонали ', diag_sum)

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
Сумма значений по диагонали  45


**Задание 3**
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3  


In [29]:
from numpy import linalg as la

a = np.array([[4,2,1],[1,3,0],[0,5,4]])
b = np.array([4,12,-3])
x = la.solve(a, b)
print (x)


[ 0.46666667  3.84444444 -5.55555556]


In [34]:
np.allclose( np.dot(a,x), b ) #Проверка


True